//! Tests for `scripts/check-versions.sh`, the release version-consistency
//! guard. Every fixture lives under a `tempfile::TempDir`, so no test ever
//! touches this repo's real `Cargo.toml`/`Cargo.lock`/plugin manifests.

use std::path::Path;
use std::process::{Command, Output};
use tempfile::TempDir;

/// The four version sources the script checks, plus the two JSON files it
/// only syntax-checks. All default to the same version so a single field
/// can be overridden per test to produce a targeted mismatch.
struct Versions<'a> {
    cargo_toml: &'a str,
    cargo_lock: &'a str,
    plugin_json: &'a str,
    marketplace_json: &'a str,
}

impl<'a> Versions<'a> {
    fn matching(version: &'a str) -> Self {
        Self {
            cargo_toml: version,
            cargo_lock: version,
            plugin_json: version,
            marketplace_json: version,
        }
    }
}

/// Writes a fixture tree that mirrors the real repo's version-bearing
/// files. `Cargo.toml` and `Cargo.lock` each carry a decoy dependency whose
/// own "version" line differs, to prove the script's parser is scoped to
/// the right section/package rather than grabbing the first match.
fn write_fixture(root: &Path, v: &Versions<'_>) {
    std::fs::create_dir_all(root.join(".claude-plugin")).unwrap();

    std::fs::write(
        root.join("Cargo.toml"),
        format!(
            r#"[package]
name = "typemux-cc"
version = "{}"
edition = "2021"

[dependencies]
serde = {{ version = "1.0" }}
"#,
            v.cargo_toml
        ),
    )
    .unwrap();

    std::fs::write(
        root.join("Cargo.lock"),
        format!(
            r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "typemux-cc"
version = "{}"
dependencies = [
 "serde",
]
"#,
            v.cargo_lock
        ),
    )
    .unwrap();

    std::fs::write(
        root.join(".claude-plugin/plugin.json"),
        format!(
            r#"{{"name": "typemux-cc", "version": "{}"}}"#,
            v.plugin_json
        ),
    )
    .unwrap();

    std::fs::write(
        root.join(".claude-plugin/marketplace.json"),
        format!(
            r#"{{"name": "typemux-cc-marketplace", "plugins": [{{"name": "typemux-cc", "version": "{}"}}]}}"#,
            v.marketplace_json
        ),
    )
    .unwrap();

    std::fs::write(root.join("hooks.json"), "{}").unwrap();
    std::fs::write(root.join(".lsp.json"), "{}").unwrap();
}

fn run_check(root: &Path, extra_args: &[&str]) -> Output {
    let script = format!("{}/scripts/check-versions.sh", env!("CARGO_MANIFEST_DIR"));
    Command::new(script)
        .arg("--root")
        .arg(root)
        .args(extra_args)
        .output()
        .expect("failed to run check-versions.sh")
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).to_string()
}

/// `scripts/check-versions.sh` requires `jq`. Tests print a skip notice and
/// return early rather than fail when it's absent, so a missing optional
/// dev tool is never mistaken for a real assertion failure.
fn jq_available() -> bool {
    let available = Command::new("jq")
        .arg("--version")
        .output()
        .is_ok_and(|o| o.status.success());
    if !available {
        println!(
            "skipping: jq not found in PATH (required by scripts/check-versions.sh); \
             install with `brew install jq` or `apt-get install -y jq`"
        );
    }
    available
}

#[test]
fn matching_versions_pass() {
    if !jq_available() {
        return;
    }
    let temp = TempDir::new().unwrap();
    write_fixture(temp.path(), &Versions::matching("1.2.3"));

    let output = run_check(temp.path(), &[]);

    assert!(output.status.success(), "stderr: {}", stderr(&output));
    assert!(String::from_utf8_lossy(&output.stdout).contains("1.2.3"));
}

#[test]
fn cargo_toml_mismatch_fails_and_reports_value() {
    if !jq_available() {
        return;
    }
    let temp = TempDir::new().unwrap();
    let mut v = Versions::matching("1.2.3");
    v.cargo_toml = "9.9.9";
    write_fixture(temp.path(), &v);

    let output = run_check(temp.path(), &[]);

    assert!(!output.status.success());
    let err = stderr(&output);
    assert!(err.contains("Cargo.toml"), "stderr: {err}");
    assert!(err.contains("9.9.9"), "stderr: {err}");
    assert!(err.contains("1.2.3"), "stderr: {err}");
}

#[test]
fn cargo_lock_mismatch_is_scoped_to_the_root_package() {
    if !jq_available() {
        return;
    }
    let temp = TempDir::new().unwrap();
    let mut v = Versions::matching("1.2.3");
    v.cargo_lock = "9.9.9";
    write_fixture(temp.path(), &v);

    let output = run_check(temp.path(), &[]);

    assert!(!output.status.success());
    let err = stderr(&output);
    assert!(err.contains("Cargo.lock"), "stderr: {err}");
    assert!(err.contains("9.9.9"), "stderr: {err}");
    // The decoy "serde" dependency's 1.0.200 must never surface as typemux-cc's version.
    assert!(!err.contains("1.0.200"), "stderr: {err}");
}

#[test]
fn plugin_json_mismatch_fails_and_reports_value() {
    if !jq_available() {
        return;
    }
    let temp = TempDir::new().unwrap();
    let mut v = Versions::matching("1.2.3");
    v.plugin_json = "9.9.9";
    write_fixture(temp.path(), &v);

    let output = run_check(temp.path(), &[]);

    assert!(!output.status.success());
    let err = stderr(&output);
    assert!(err.contains("plugin.json"), "stderr: {err}");
    assert!(err.contains("9.9.9"), "stderr: {err}");
}

#[test]
fn marketplace_json_mismatch_fails_and_reports_value() {
    if !jq_available() {
        return;
    }
    let temp = TempDir::new().unwrap();
    let mut v = Versions::matching("1.2.3");
    v.marketplace_json = "9.9.9";
    write_fixture(temp.path(), &v);

    let output = run_check(temp.path(), &[]);

    assert!(!output.status.success());
    let err = stderr(&output);
    assert!(err.contains("marketplace.json"), "stderr: {err}");
    assert!(err.contains("9.9.9"), "stderr: {err}");
}

#[test]
fn malformed_json_fails_and_names_the_file() {
    if !jq_available() {
        return;
    }
    let temp = TempDir::new().unwrap();
    write_fixture(temp.path(), &Versions::matching("1.2.3"));
    std::fs::write(
        temp.path().join(".claude-plugin/marketplace.json"),
        "{not valid json",
    )
    .unwrap();

    let output = run_check(temp.path(), &[]);

    assert!(!output.status.success());
    let err = stderr(&output);
    assert!(err.contains("marketplace.json"), "stderr: {err}");
}

#[test]
fn release_tag_matching_version_passes() {
    if !jq_available() {
        return;
    }
    let temp = TempDir::new().unwrap();
    write_fixture(temp.path(), &Versions::matching("1.2.3"));

    let output = run_check(temp.path(), &["--release", "v1.2.3"]);

    assert!(output.status.success(), "stderr: {}", stderr(&output));
}

#[test]
fn release_tag_mismatch_fails_and_reports_both_values() {
    if !jq_available() {
        return;
    }
    let temp = TempDir::new().unwrap();
    write_fixture(temp.path(), &Versions::matching("1.2.3"));

    let output = run_check(temp.path(), &["--release", "v9.9.9"]);

    assert!(!output.status.success());
    let err = stderr(&output);
    assert!(err.contains("v9.9.9"), "stderr: {err}");
    assert!(err.contains("v1.2.3"), "stderr: {err}");
}

/// Guards this repo's own committed files, not just the fixture logic
/// above: fails if a real version bump ever forgets one of the four files.
#[test]
fn real_repo_versions_agree() {
    if !jq_available() {
        return;
    }
    let output = run_check(Path::new(env!("CARGO_MANIFEST_DIR")), &[]);

    assert!(output.status.success(), "stderr: {}", stderr(&output));
}
